apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7ehb
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7ehb
    app.kubernetes.io/part-of: syahmed-quay-ui
  name: devfile-sample-7ehb
  namespace: syahmed-tenant
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-7ehb
status:
  loadBalancer: {}
